-- MySQL Script generated by MySQL Workbench
-- Wed Aug 10 11:22:04 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema htrcvirtdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema htrcvirtdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `htrcvirtdb` DEFAULT CHARACTER SET utf8 ;
USE `htrcvirtdb` ;

-- -----------------------------------------------------
-- Table `htrcvirtdb`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `htrcvirtdb`.`images` ;

CREATE TABLE IF NOT EXISTS `htrcvirtdb`.`images` (
  `imagename` VARCHAR(128) NOT NULL,
  `imagedescription` VARCHAR(1024) NULL,
  `imagepath` VARCHAR(512) NULL,
  `loginusername` VARCHAR(32) NULL,
  `loginpassword` VARCHAR(128) NULL,
  PRIMARY KEY (`imagename`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `htrcvirtdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `htrcvirtdb`.`users` ;

CREATE TABLE IF NOT EXISTS `htrcvirtdb`.`users` (
  `username` VARCHAR(128) NOT NULL,
  `useremail` VARCHAR(128) NULL,
  `cpuleftquota` INT NULL,
  `memoryleftquota` INT NULL,
  `diskleftquota` INT NULL,
  `usertype` VARCHAR(64) NULL DEFAULT 'regular',
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `htrcvirtdb`.`vmhosts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `htrcvirtdb`.`vmhosts` ;

CREATE TABLE IF NOT EXISTS `htrcvirtdb`.`vmhosts` (
  `hostname` VARCHAR(256) NOT NULL,
  `cpu_cores` INT NULL,
  `mem_gb` INT NULL,
  PRIMARY KEY (`hostname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `htrcvirtdb`.`vms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `htrcvirtdb`.`vms` ;

CREATE TABLE IF NOT EXISTS `htrcvirtdb`.`vms` (
  `vmid` VARCHAR(128) NOT NULL,
  `vmmode` ENUM('MAINTENANCE', 'SECURE', 'NOT_DEFINED') NULL,
  `vmstate` ENUM('CREATE_PENDING','LAUNCH_PENDING','RUNNING','SWITCH_TO_MAINTENANCE_PENDING','SWITCH_TO_SECURE_PENDING','SHUTDOWN_PENDING','SHUTDOWN','DELETE_PENDING','ERROR') NULL,
  `sshport` INT NULL,
  `vncport` INT NULL,
  `workingdir` VARCHAR(512) NULL,
  `imagename` VARCHAR(128) NULL,
  `vncusername` VARCHAR(128) NULL,
  `vncpassword` VARCHAR(128) NULL,
  `numcpus` INT NULL,
  `memorysize` INT NULL,
  `diskspace` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` VARCHAR(128) NOT NULL,
  `host` VARCHAR(256) NULL,
  PRIMARY KEY (`vmid`),
  INDEX `fk_images_idx` (`imagename` ASC),
  INDEX `fk_users_idx` (`username` ASC),
  INDEX `fk_host_idx` (`host` ASC),
  CONSTRAINT `fk_images`
    FOREIGN KEY (`imagename`)
    REFERENCES `htrcvirtdb`.`images` (`imagename`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users`
    FOREIGN KEY (`username`)
    REFERENCES `htrcvirtdb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_host`
    FOREIGN KEY (`host`)
    REFERENCES `htrcvirtdb`.`vmhosts` (`hostname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `htrcvirtdb`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `htrcvirtdb`.`results` ;

CREATE TABLE IF NOT EXISTS `htrcvirtdb`.`results` (
  `vmid` VARCHAR(128) NOT NULL,
  `resultid` VARCHAR(256) NOT NULL,
  `datafield` LONGBLOB NULL,
  `createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `notified` ENUM('YES', 'NO', 'REJECTED') NOT NULL DEFAULT 'NO',
  `notifiedtime` TIMESTAMP NULL,
  PRIMARY KEY (`vmid`, `resultid`),
  CONSTRAINT `fk_vms`
    FOREIGN KEY (`vmid`)
    REFERENCES `htrcvirtdb`.`vms` (`vmid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `htrcvirtdb`.`vmactivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `htrcvirtdb`.`vmactivity` ;

CREATE TABLE IF NOT EXISTS `htrcvirtdb`.`vmactivity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `vmid` VARCHAR(128) NOT NULL,
  `prev_mode` ENUM('M', 'S') NOT NULL,
  `curr_mode` ENUM('M', 'S') NOT NULL,
  `prev_state` ENUM('CREATED', 'RUNNING', 'STOPED', 'ERROR', 'DELETED') NOT NULL,
  `curr_state` ENUM('CREATED', 'RUNNING', 'STOPED', 'ERROR', 'DELETED') NOT NULL,
  `username` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vmid_idx` (`vmid` ASC),
  INDEX `fk_username_idx` (`username` ASC),
  CONSTRAINT `fk_vmid`
    FOREIGN KEY (`vmid`)
    REFERENCES `htrcvirtdb`.`vms` (`vmid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_username`
    FOREIGN KEY (`username`)
    REFERENCES `htrcvirtdb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
