USE htrcvirtdb;

INSERT INTO images VALUES ("<IMAGE_NAME>", "ACTIVE", "<DESCRIPTION_OF_THE_IMAGE>", "<IMAGE_PATH_IN_THE_HOST>", "<IMAGE_USER_ID>", "<IMAGE_USER_PASSWORD>");
INSERT INTO vmhosts VALUES ("<HOST_NAME>",<HOST_CPU>,<HOST_MEMORY_IN_GB>);
